
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.GovIdScalarFieldEnum = {
  id: 'id',
  govIdNumber: 'govIdNumber',
  email: 'email',
  passwordHash: 'passwordHash',
  emailVerified: 'emailVerified',
  status: 'status',
  failedLoginAttempts: 'failedLoginAttempts',
  lockedUntil: 'lockedUntil',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  govId: 'govId',
  financialPasswordHash: 'financialPasswordHash',
  displayName: 'displayName',
  role: 'role',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tokenHash: 'tokenHash',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  expiresAt: 'expiresAt',
  revoked: 'revoked',
  createdAt: 'createdAt'
};

exports.Prisma.MfaTokenScalarFieldEnum = {
  id: 'id',
  email: 'email',
  codeHash: 'codeHash',
  purpose: 'purpose',
  attempts: 'attempts',
  expiresAt: 'expiresAt',
  consumed: 'consumed',
  createdAt: 'createdAt'
};

exports.Prisma.BankScalarFieldEnum = {
  id: 'id',
  name: 'name',
  shortName: 'shortName',
  tagline: 'tagline',
  logoPath: 'logoPath',
  licenseNumber: 'licenseNumber',
  establishedDate: 'establishedDate',
  accentColor: 'accentColor',
  status: 'status',
  ownership: 'ownership',
  governingDirector: 'governingDirector',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CentralBankConfigScalarFieldEnum = {
  id: 'id',
  institutionName: 'institutionName',
  charterId: 'charterId',
  sovereignSeat: 'sovereignSeat',
  currentGovernor: 'currentGovernor',
  deputyGovernor: 'deputyGovernor',
  auditQuorumCount: 'auditQuorumCount',
  sessionTimeoutMinutes: 'sessionTimeoutMinutes',
  dualPasswordEnforced: 'dualPasswordEnforced',
  ipWhitelistEnforced: 'ipWhitelistEnforced',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BankCustomerScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  bankId: 'bankId',
  customerNumber: 'customerNumber',
  status: 'status',
  tier: 'tier',
  joinedAt: 'joinedAt'
};

exports.Prisma.BankAccountScalarFieldEnum = {
  id: 'id',
  accountNumber: 'accountNumber',
  customerId: 'customerId',
  bankId: 'bankId',
  userId: 'userId',
  type: 'type',
  purpose: 'purpose',
  status: 'status',
  dailyLimitMinor: 'dailyLimitMinor',
  monthlyLimitMinor: 'monthlyLimitMinor',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LedgerAccountScalarFieldEnum = {
  id: 'id',
  accountType: 'accountType',
  ownerEntityId: 'ownerEntityId',
  ownerEntityType: 'ownerEntityType',
  balanceSnapshot: 'balanceSnapshot',
  snapshotAt: 'snapshotAt',
  bankAccountId: 'bankAccountId',
  createdAt: 'createdAt'
};

exports.Prisma.TransactionEntryScalarFieldEnum = {
  id: 'id',
  transactionId: 'transactionId',
  ledgerAccountId: 'ledgerAccountId',
  entryType: 'entryType',
  amountMinor: 'amountMinor',
  createdAt: 'createdAt'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  referenceNumber: 'referenceNumber',
  type: 'type',
  status: 'status',
  scope: 'scope',
  amountMinor: 'amountMinor',
  feesMinor: 'feesMinor',
  taxMinor: 'taxMinor',
  initiatedBy: 'initiatedBy',
  sourceAccountId: 'sourceAccountId',
  destinationAccountId: 'destinationAccountId',
  settlementId: 'settlementId',
  failureReason: 'failureReason',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SettlementScalarFieldEnum = {
  id: 'id',
  reference: 'reference',
  sourceBankId: 'sourceBankId',
  destinationBankId: 'destinationBankId',
  amountMinor: 'amountMinor',
  feeLevyMinor: 'feeLevyMinor',
  stage: 'stage',
  clearingLatencyMs: 'clearingLatencyMs',
  failureReason: 'failureReason',
  reversalTransactionId: 'reversalTransactionId',
  timeline: 'timeline',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BeneficiaryScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  beneficiaryName: 'beneficiaryName',
  accountNumber: 'accountNumber',
  bankId: 'bankId',
  nickname: 'nickname',
  createdAt: 'createdAt'
};

exports.Prisma.FdSchemeScalarFieldEnum = {
  id: 'id',
  bankId: 'bankId',
  name: 'name',
  tenureDays: 'tenureDays',
  baseApy: 'baseApy',
  seniorApy: 'seniorApy',
  minimumDepositMinor: 'minimumDepositMinor',
  maximumDepositMinor: 'maximumDepositMinor',
  lockInDays: 'lockInDays',
  preclosurePenaltyRate: 'preclosurePenaltyRate',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserFdScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  accountId: 'accountId',
  bankId: 'bankId',
  schemeId: 'schemeId',
  certificateNumber: 'certificateNumber',
  principalMinor: 'principalMinor',
  maturityAmountMinor: 'maturityAmountMinor',
  apy: 'apy',
  status: 'status',
  startDate: 'startDate',
  maturityDate: 'maturityDate',
  interestPayoutFreq: 'interestPayoutFreq',
  accruedInterestMinor: 'accruedInterestMinor',
  autoRenew: 'autoRenew',
  rolloverInstruction: 'rolloverInstruction',
  closedAt: 'closedAt',
  payoutAmountMinor: 'payoutAmountMinor',
  payoutTxId: 'payoutTxId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InterestPayoutLogScalarFieldEnum = {
  id: 'id',
  userFdId: 'userFdId',
  userId: 'userId',
  transactionId: 'transactionId',
  grossAmountMinor: 'grossAmountMinor',
  taxWithheldMinor: 'taxWithheldMinor',
  netAmountMinor: 'netAmountMinor',
  payoutDate: 'payoutDate',
  payoutType: 'payoutType'
};

exports.Prisma.LoanScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  bankId: 'bankId',
  loanType: 'loanType',
  principalMinor: 'principalMinor',
  interestRateApy: 'interestRateApy',
  tenureMonths: 'tenureMonths',
  monthlyEmiMinor: 'monthlyEmiMinor',
  outstandingBalanceMinor: 'outstandingBalanceMinor',
  status: 'status',
  appliedDate: 'appliedDate',
  disbursedDate: 'disbursedDate',
  purpose: 'purpose',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BankProductScalarFieldEnum = {
  id: 'id',
  bankId: 'bankId',
  name: 'name',
  category: 'category',
  description: 'description',
  minBalanceMinor: 'minBalanceMinor',
  features: 'features',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OperationQueueScalarFieldEnum = {
  id: 'id',
  bankId: 'bankId',
  type: 'type',
  referenceId: 'referenceId',
  title: 'title',
  description: 'description',
  assignedStaffId: 'assignedStaffId',
  status: 'status',
  priority: 'priority',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StockCompanyScalarFieldEnum = {
  symbol: 'symbol',
  name: 'name',
  sector: 'sector',
  currentPriceMinor: 'currentPriceMinor',
  openingPriceMinor: 'openingPriceMinor',
  dayHighMinor: 'dayHighMinor',
  dayLowMinor: 'dayLowMinor',
  previousCloseMinor: 'previousCloseMinor',
  changePercent: 'changePercent',
  volume: 'volume',
  marketCapMinor: 'marketCapMinor',
  peRatio: 'peRatio',
  circuitLimitLowMinor: 'circuitLimitLowMinor',
  circuitLimitHighMinor: 'circuitLimitHighMinor',
  circuitBreakerActive: 'circuitBreakerActive',
  sharesOutstanding: 'sharesOutstanding',
  freeFloatPercent: 'freeFloatPercent',
  dividendYield: 'dividendYield',
  description: 'description',
  listedDate: 'listedDate',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StockTickerScalarFieldEnum = {
  id: 'id',
  symbol: 'symbol',
  priceMinor: 'priceMinor',
  volume: 'volume',
  changePercent: 'changePercent',
  timestamp: 'timestamp'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  symbol: 'symbol',
  side: 'side',
  type: 'type',
  quantity: 'quantity',
  filledQuantity: 'filledQuantity',
  priceMinor: 'priceMinor',
  status: 'status',
  sourceAccountId: 'sourceAccountId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TradeScalarFieldEnum = {
  id: 'id',
  buyOrderId: 'buyOrderId',
  sellOrderId: 'sellOrderId',
  symbol: 'symbol',
  priceMinor: 'priceMinor',
  quantity: 'quantity',
  buyerUserId: 'buyerUserId',
  sellerUserId: 'sellerUserId',
  buyerFeeMinor: 'buyerFeeMinor',
  sellerFeeMinor: 'sellerFeeMinor',
  taxLevyMinor: 'taxLevyMinor',
  settlementStage: 'settlementStage',
  executedAt: 'executedAt'
};

exports.Prisma.PortfolioHoldingScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  symbol: 'symbol',
  shares: 'shares',
  averageBuyPriceMinor: 'averageBuyPriceMinor',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaxEventScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  symbol: 'symbol',
  sharesSold: 'sharesSold',
  sellPriceMinor: 'sellPriceMinor',
  buyPriceMinor: 'buyPriceMinor',
  realizedProfitMinor: 'realizedProfitMinor',
  taxRatePercent: 'taxRatePercent',
  taxAmountMinor: 'taxAmountMinor',
  offsetAppliedMinor: 'offsetAppliedMinor',
  executedAt: 'executedAt'
};

exports.Prisma.ThematicBasketScalarFieldEnum = {
  id: 'id',
  name: 'name',
  tagline: 'tagline',
  description: 'description',
  riskTier: 'riskTier',
  rebalanceSchedule: 'rebalanceSchedule',
  basketComposition: 'basketComposition',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ShopItemScalarFieldEnum = {
  id: 'id',
  name: 'name',
  category: 'category',
  rarity: 'rarity',
  priceMinor: 'priceMinor',
  image: 'image',
  secondaryImage: 'secondaryImage',
  rank: 'rank',
  role: 'role',
  gender: 'gender',
  powerTitle: 'powerTitle',
  powerDescription: 'powerDescription',
  attireSpec: 'attireSpec',
  accreditation: 'accreditation',
  covenantSection: 'covenantSection',
  perks: 'perks',
  active: 'active',
  status: 'status',
  ownershipType: 'ownershipType',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserInventoryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  itemId: 'itemId',
  acquiredAt: 'acquiredAt'
};

exports.Prisma.UserLoadoutScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  frameId: 'frameId',
  avatarId: 'avatarId',
  bannerId: 'bannerId',
  petId: 'petId',
  updatedAt: 'updatedAt'
};

exports.Prisma.RewardTaskScalarFieldEnum = {
  id: 'id',
  title: 'title',
  category: 'category',
  description: 'description',
  rewardMinor: 'rewardMinor',
  active: 'active',
  createdAt: 'createdAt'
};

exports.Prisma.RewardAchievementScalarFieldEnum = {
  id: 'id',
  title: 'title',
  badgeName: 'badgeName',
  icon: 'icon',
  criteria: 'criteria',
  rewardMinor: 'rewardMinor',
  active: 'active',
  createdAt: 'createdAt'
};

exports.Prisma.RewardTransactionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  taskId: 'taskId',
  achievementId: 'achievementId',
  amountMinor: 'amountMinor',
  transactionId: 'transactionId',
  claimedAt: 'claimedAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  category: 'category',
  priority: 'priority',
  title: 'title',
  summary: 'summary',
  content: 'content',
  templateCode: 'templateCode',
  templateVersion: 'templateVersion',
  sourceDomain: 'sourceDomain',
  sourceType: 'sourceType',
  sourceId: 'sourceId',
  eventId: 'eventId',
  metadata: 'metadata',
  isRead: 'isRead',
  readAt: 'readAt',
  isArchived: 'isArchived',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AnnouncementScalarFieldEnum = {
  id: 'id',
  title: 'title',
  category: 'category',
  audience: 'audience',
  status: 'status',
  publishedAt: 'publishedAt',
  authorCouncil: 'authorCouncil',
  summary: 'summary',
  fullBody: 'fullBody',
  reachesCitizenMailbox: 'reachesCitizenMailbox',
  priority: 'priority',
  createdAt: 'createdAt'
};

exports.Prisma.MailboxMessageScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  announcementId: 'announcementId',
  title: 'title',
  category: 'category',
  sender: 'sender',
  body: 'body',
  read: 'read',
  priority: 'priority',
  receivedAt: 'receivedAt'
};

exports.Prisma.FinancialRuleScalarFieldEnum = {
  id: 'id',
  key: 'key',
  title: 'title',
  currentValue: 'currentValue',
  unit: 'unit',
  category: 'category',
  description: 'description',
  version: 'version',
  lastModified: 'lastModified',
  modifiedBy: 'modifiedBy',
  effectiveDate: 'effectiveDate',
  statutoryBasis: 'statutoryBasis',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaxRuleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  category: 'category',
  ratePercent: 'ratePercent',
  thresholdMinor: 'thresholdMinor',
  description: 'description',
  version: 'version',
  effectiveFrom: 'effectiveFrom',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MonetaryEventScalarFieldEnum = {
  id: 'id',
  eventType: 'eventType',
  amountMinor: 'amountMinor',
  authorizedBy: 'authorizedBy',
  reason: 'reason',
  transactionId: 'transactionId',
  createdAt: 'createdAt'
};

exports.Prisma.SystemLogScalarFieldEnum = {
  id: 'id',
  eventType: 'eventType',
  actorId: 'actorId',
  actorRole: 'actorRole',
  targetEntity: 'targetEntity',
  action: 'action',
  severity: 'severity',
  ipAddress: 'ipAddress',
  sessionHash: 'sessionHash',
  beforeState: 'beforeState',
  afterState: 'afterState',
  timestamp: 'timestamp'
};

exports.Prisma.SecurityEventScalarFieldEnum = {
  id: 'id',
  eventType: 'eventType',
  targetEntity: 'targetEntity',
  severity: 'severity',
  ipAddress: 'ipAddress',
  actionTaken: 'actionTaken',
  metadata: 'metadata',
  timestamp: 'timestamp'
};

exports.Prisma.LoanProductScalarFieldEnum = {
  id: 'id',
  bankId: 'bankId',
  name: 'name',
  category: 'category',
  description: 'description',
  baseInterestRate: 'baseInterestRate',
  minPrincipalMinor: 'minPrincipalMinor',
  maxPrincipalMinor: 'maxPrincipalMinor',
  minTenureMonths: 'minTenureMonths',
  maxTenureMonths: 'maxTenureMonths',
  processingFeePercent: 'processingFeePercent',
  collateralRequired: 'collateralRequired',
  minCollateralRatioPercent: 'minCollateralRatioPercent',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserLoanScalarFieldEnum = {
  id: 'id',
  contractNumber: 'contractNumber',
  userId: 'userId',
  bankId: 'bankId',
  productId: 'productId',
  disbursementAccountId: 'disbursementAccountId',
  repaymentAccountId: 'repaymentAccountId',
  loanType: 'loanType',
  status: 'status',
  principalMinor: 'principalMinor',
  interestRate: 'interestRate',
  tenureMonths: 'tenureMonths',
  monthlyEmiMinor: 'monthlyEmiMinor',
  outstandingPrincipalMinor: 'outstandingPrincipalMinor',
  totalRepaidPrincipalMinor: 'totalRepaidPrincipalMinor',
  totalRepaidInterestMinor: 'totalRepaidInterestMinor',
  purpose: 'purpose',
  appliedAt: 'appliedAt',
  approvedAt: 'approvedAt',
  disbursedAt: 'disbursedAt',
  closedAt: 'closedAt',
  rejectionReason: 'rejectionReason',
  approvedByStaffId: 'approvedByStaffId',
  notes: 'notes',
  idempotencyKey: 'idempotencyKey',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LoanInstallmentScalarFieldEnum = {
  id: 'id',
  loanId: 'loanId',
  installmentNumber: 'installmentNumber',
  dueDate: 'dueDate',
  principalMinor: 'principalMinor',
  interestMinor: 'interestMinor',
  totalAmountMinor: 'totalAmountMinor',
  remainingPrincipalMinor: 'remainingPrincipalMinor',
  status: 'status',
  paidAt: 'paidAt',
  transactionId: 'transactionId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LoanCollateralScalarFieldEnum = {
  id: 'id',
  loanId: 'loanId',
  collateralType: 'collateralType',
  assetReferenceId: 'assetReferenceId',
  appraisedValueMinor: 'appraisedValueMinor',
  lienStatus: 'lienStatus',
  lockedAt: 'lockedAt',
  releasedAt: 'releasedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.GovIdStatus = exports.$Enums.GovIdStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  LOCKED: 'LOCKED'
};

exports.UserRole = exports.$Enums.UserRole = {
  USER: 'USER',
  BANK_ADMIN: 'BANK_ADMIN',
  CENTRAL_BANK_ADMIN: 'CENTRAL_BANK_ADMIN'
};

exports.UserStatus = exports.$Enums.UserStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  LOCKED: 'LOCKED',
  CLOSED: 'CLOSED'
};

exports.MfaPurpose = exports.$Enums.MfaPurpose = {
  EMAIL_VERIFY: 'EMAIL_VERIFY',
  PASSWORD_RESET: 'PASSWORD_RESET',
  STEP_UP: 'STEP_UP'
};

exports.BankAccountType = exports.$Enums.BankAccountType = {
  SAVINGS: 'SAVINGS',
  CURRENT: 'CURRENT'
};

exports.BankAccountStatus = exports.$Enums.BankAccountStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  FROZEN: 'FROZEN',
  CLOSED: 'CLOSED',
  DORMANT: 'DORMANT'
};

exports.LedgerAccountType = exports.$Enums.LedgerAccountType = {
  BANK_ACCOUNT: 'BANK_ACCOUNT',
  BANK_RESERVE: 'BANK_RESERVE',
  CENTRAL_TREASURY: 'CENTRAL_TREASURY',
  TAX_AUTHORITY: 'TAX_AUTHORITY',
  FEE_POOL: 'FEE_POOL',
  STOCK_EXCHANGE: 'STOCK_EXCHANGE',
  SHOP_REVENUE: 'SHOP_REVENUE',
  REWARD_POOL: 'REWARD_POOL',
  LOAN_POOL: 'LOAN_POOL',
  FD_POOL: 'FD_POOL',
  CLS_CLEARING: 'CLS_CLEARING'
};

exports.TransactionEntryType = exports.$Enums.TransactionEntryType = {
  DEBIT: 'DEBIT',
  CREDIT: 'CREDIT'
};

exports.TransactionType = exports.$Enums.TransactionType = {
  TRANSFER: 'TRANSFER',
  DEPOSIT: 'DEPOSIT',
  WITHDRAWAL: 'WITHDRAWAL',
  INTEREST: 'INTEREST',
  FEE: 'FEE',
  TAX: 'TAX',
  LOAN_DISBURSEMENT: 'LOAN_DISBURSEMENT',
  LOAN_REPAYMENT: 'LOAN_REPAYMENT',
  FD_BOOKING: 'FD_BOOKING',
  FD_MATURITY: 'FD_MATURITY',
  STOCK_BUY: 'STOCK_BUY',
  STOCK_SELL: 'STOCK_SELL',
  SHOP_PURCHASE: 'SHOP_PURCHASE',
  REWARD: 'REWARD',
  REVERSAL: 'REVERSAL',
  MINT: 'MINT',
  BURN: 'BURN'
};

exports.TransactionStatus = exports.$Enums.TransactionStatus = {
  PENDING: 'PENDING',
  VALIDATING: 'VALIDATING',
  AUTHORIZED: 'AUTHORIZED',
  PROCESSING: 'PROCESSING',
  SETTLING: 'SETTLING',
  FINALIZING: 'FINALIZING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REVERSED: 'REVERSED',
  CANCELLED: 'CANCELLED'
};

exports.TransactionScope = exports.$Enums.TransactionScope = {
  INTERNAL: 'INTERNAL',
  INTER_BANK: 'INTER_BANK'
};

exports.SettlementStage = exports.$Enums.SettlementStage = {
  VALIDATING: 'VALIDATING',
  AUTHORIZED: 'AUTHORIZED',
  PROCESSING: 'PROCESSING',
  SETTLING: 'SETTLING',
  FINALIZING: 'FINALIZING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REVERSED: 'REVERSED'
};

exports.FdStatus = exports.$Enums.FdStatus = {
  ACTIVE: 'ACTIVE',
  MATURED: 'MATURED',
  BROKEN: 'BROKEN',
  PENDING: 'PENDING'
};

exports.LoanStatus = exports.$Enums.LoanStatus = {
  APPLIED: 'APPLIED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  DISBURSED: 'DISBURSED',
  REPAID: 'REPAID',
  DEFAULTED: 'DEFAULTED',
  REJECTED: 'REJECTED'
};

exports.OrderSide = exports.$Enums.OrderSide = {
  BUY: 'BUY',
  SELL: 'SELL'
};

exports.OrderType = exports.$Enums.OrderType = {
  LIMIT: 'LIMIT',
  MARKET: 'MARKET',
  STOP: 'STOP'
};

exports.OrderStatus = exports.$Enums.OrderStatus = {
  OPEN: 'OPEN',
  PARTIALLY_FILLED: 'PARTIALLY_FILLED',
  FILLED: 'FILLED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  REJECTED: 'REJECTED'
};

exports.TradeStatus = exports.$Enums.TradeStatus = {
  SETTLING: 'SETTLING',
  SETTLED: 'SETTLED',
  FAILED: 'FAILED'
};

exports.ShopCategory = exports.$Enums.ShopCategory = {
  all: 'all',
  pets: 'pets',
  avatars: 'avatars',
  frames: 'frames',
  banners: 'banners',
  inventory: 'inventory'
};

exports.RarityTier = exports.$Enums.RarityTier = {
  normal: 'normal',
  rare: 'rare',
  epic: 'epic',
  gold: 'gold'
};

exports.NotificationCategory = exports.$Enums.NotificationCategory = {
  TRANSFER: 'TRANSFER',
  SETTLEMENT: 'SETTLEMENT',
  STOCK: 'STOCK',
  SHOP: 'SHOP',
  FD: 'FD',
  LOAN: 'LOAN',
  REWARD: 'REWARD',
  SYSTEM: 'SYSTEM',
  SECURITY: 'SECURITY',
  POLICY: 'POLICY'
};

exports.NotificationPriority = exports.$Enums.NotificationPriority = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

exports.AuditSeverity = exports.$Enums.AuditSeverity = {
  INFO: 'INFO',
  NOTICE: 'NOTICE',
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL'
};

exports.Prisma.ModelName = {
  GovId: 'GovId',
  User: 'User',
  Session: 'Session',
  MfaToken: 'MfaToken',
  Bank: 'Bank',
  CentralBankConfig: 'CentralBankConfig',
  BankCustomer: 'BankCustomer',
  BankAccount: 'BankAccount',
  LedgerAccount: 'LedgerAccount',
  TransactionEntry: 'TransactionEntry',
  Transaction: 'Transaction',
  Settlement: 'Settlement',
  Beneficiary: 'Beneficiary',
  FdScheme: 'FdScheme',
  UserFd: 'UserFd',
  InterestPayoutLog: 'InterestPayoutLog',
  Loan: 'Loan',
  BankProduct: 'BankProduct',
  OperationQueue: 'OperationQueue',
  StockCompany: 'StockCompany',
  StockTicker: 'StockTicker',
  Order: 'Order',
  Trade: 'Trade',
  PortfolioHolding: 'PortfolioHolding',
  TaxEvent: 'TaxEvent',
  ThematicBasket: 'ThematicBasket',
  ShopItem: 'ShopItem',
  UserInventory: 'UserInventory',
  UserLoadout: 'UserLoadout',
  RewardTask: 'RewardTask',
  RewardAchievement: 'RewardAchievement',
  RewardTransaction: 'RewardTransaction',
  Notification: 'Notification',
  Announcement: 'Announcement',
  MailboxMessage: 'MailboxMessage',
  FinancialRule: 'FinancialRule',
  TaxRule: 'TaxRule',
  MonetaryEvent: 'MonetaryEvent',
  SystemLog: 'SystemLog',
  SecurityEvent: 'SecurityEvent',
  LoanProduct: 'LoanProduct',
  UserLoan: 'UserLoan',
  LoanInstallment: 'LoanInstallment',
  LoanCollateral: 'LoanCollateral'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
