import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Stitch Sovereign M3 Palette
        'primary': '#022448',
        'primary-container': '#1e3a5f',
        'on-primary': '#ffffff',
        'on-primary-container': '#8aa4cf',
        'inverse-primary': '#adc8f5',
        'secondary': '#4c5d8e',
        'secondary-container': '#dbe1ff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#405181',
        'tertiary': '#361f00',
        'tertiary-container': '#533300',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#d2984b',
        'gold-accent': '#A8742A',
        'gold-light': '#FDF8F0',
        'gold-border': '#DFB87A',
        'surface': '#f8f9ff',
        'surface-dim': '#d1dbeb',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef4ff',
        'surface-container': '#e5efff',
        'surface-container-high': '#dfe9fa',
        'surface-container-highest': '#d9e3f4',
        'on-surface': '#121c28',
        'on-surface-variant': '#43474e',
        'inverse-surface': '#27313e',
        'inverse-on-surface': '#eaf1ff',
        'outline': '#74777f',
        'outline-variant': '#c4c6cf',
        'surface-tint': '#455f87',
        'emerald-live': '#10B981',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        // Canonical ARTHAX tokens
        'deep-blue': '#1E3A5F',
        'soft-blue': '#66A3BF',
        'sage-mint': '#C8DFDB',
        'off-white': '#F2EFE7',
        'arth-gold': '#A8742A',
        'arth-gold-soft': '#FDF8F0',
        'ink': '#121C28',
        'ink-soft': '#43474E',
        'ink-muted': '#74777F',
        'positive': '#10B981',
        'loss': '#B5482E',
        'warning': '#A8742A',
        'info': '#496C80',
      },
      fontFamily: {
        serif: ['Newsreader', 'Fraunces', 'Georgia', 'serif'],
        sans: ['Inter', 'Cantarell', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
        display: ['Newsreader', 'Fraunces', 'Georgia', 'serif'],
        body: ['Inter', 'Cantarell', 'sans-serif'],
        accent: ['Amarante', 'cursive'],
      },
      borderRadius: {
        'xs': '0.125rem',
        'sm': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1.25rem',
        '3xl': '1.75rem',
        '4xl': '2.25rem',
        'full': '9999px',
      },
      boxShadow: {
        'm3-1': '0px 1px 3px 1px rgba(0, 0, 0, 0.05), 0px 1px 2px 0px rgba(0, 0, 0, 0.08)',
        'm3-2': '0px 2px 6px 2px rgba(0, 0, 0, 0.06), 0px 1px 2px 0px rgba(0, 0, 0, 0.08)',
        'm3-3': '0px 4px 12px 3px rgba(0, 0, 0, 0.07), 0px 1px 3px 0px rgba(0, 0, 0, 0.1)',
        'm3-hover': '0px 12px 32px rgba(2, 36, 72, 0.12)',
      },
    },
  },
  plugins: [],
};

export default config;
