export const colors = {
  surface: '#f8f9ff',
  surfaceDim: '#d1dbeb',
  surfaceBright: '#f8f9ff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#eef4ff',
  surfaceContainer: '#e5efff',
  surfaceContainerHigh: '#dfe9fa',
  surfaceContainerHighest: '#d9e3f4',
  onSurface: '#121c28',
  onSurfaceVariant: '#43474e',
  inverseSurface: '#27313e',
  inverseOnSurface: '#eaf1ff',
  outline: '#74777f',
  outlineVariant: '#c4c6cf',
  surfaceTint: '#455f87',
  primary: '#022448',
  onPrimary: '#ffffff',
  primaryContainer: '#1e3a5f',
  onPrimaryContainer: '#8aa4cf',
  inversePrimary: '#adc8f5',
  secondary: '#4c5d8e',
  onSecondary: '#ffffff',
  secondaryContainer: '#b4c5fd',
  onSecondaryContainer: '#405181',
  tertiary: '#361f00',
  onTertiary: '#ffffff',
  tertiaryContainer: '#533300',
  onTertiaryContainer: '#d2984b',
  goldAccent: '#a8742a',
  goldLight: '#fdf8f0',
  goldBorder: '#dfb87a',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  positive: '#10b981',
  loss: '#b5482e',
  warning: '#a8742a',
  info: '#496c80',
} as const;

export const fonts = {
  display: "'Newsreader', 'Fraunces', Georgia, serif",
  headline: "'Newsreader', 'Fraunces', Georgia, serif",
  body: "'Inter', 'Cantarell', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  mono: "'JetBrains Mono', ui-monospace, SFMono-Regular, monospace",
  accent: "'Amarante', cursive",
} as const;

export const rounded = {
  sm: '0.125rem',
  DEFAULT: '0.25rem',
  md: '0.375rem',
  lg: '0.5rem',
  xl: '0.75rem',
  full: '9999px',
} as const;

export const spacing = {
  space3xs: '0.125rem',
  space2xs: '0.25rem',
  spaceXs: '0.5rem',
  spaceSm: '0.75rem',
  spaceMd: '1rem',
  spaceLg: '1.5rem',
  spaceXl: '2rem',
  space2xl: '3rem',
  space3xl: '4rem',
  space4xl: '6rem',
  gutterMobile: '1rem',
  gutterDesktop: '2rem',
  maxWidthContent: '84rem',
} as const;
