export interface ListedCompany {
  symbol: string;
  name: string;
  isin: string;
  sector: string;
  category: 'Equities' | 'Infra' | 'Energy' | 'Defense' | 'Health' | 'Banking' | 'Tech';
  price: number;
  change: number;
  changePercent: number;
  isPositive: boolean;
  marketCap: string;
  marketCapNum: number; // in ARTH
  pe: number;
  eps: number;
  divYield: number;
  volume24h: string;
  volume24hNum: number;
  turnover: string;
  high24h: number;
  low24h: number;
  low52w: number;
  high52w: number;
  beta: number;
  stasisStatus: 'ACTIVE / STABLE' | 'AUCTION ENFORCED' | 'SETU CLEARED';
  logo: string;
  banner: string;
  description: string;
  scope: string;
  sparkline: number[];
  fundamentals: {
    revenue: string;
    netIncome: string;
    operatingMargin: string;
    totalAssets: string;
    totalDebt: string;
    freeCashFlow: string;
    roe: string;
    esgScore: number;
  };
}

export const LISTED_COMPANIES: Record<string, ListedCompany> = {
  NILA: {
    symbol: 'NILA',
    name: 'NILA Systems Ltd',
    isin: 'INE094J01018',
    sector: 'Space Mesh & Telemetry',
    category: 'Tech',
    price: 142.50,
    change: 5.64,
    changePercent: 4.12,
    isPositive: true,
    marketCap: '2.85B ARTH',
    marketCapNum: 2850000000,
    pe: 24.8,
    eps: 5.75,
    divYield: 1.45,
    volume24h: '1.24M',
    volume24hNum: 1240000,
    turnover: '176.7M ARTH',
    high24h: 144.20,
    low24h: 138.90,
    low52w: 92.40,
    high52w: 156.80,
    beta: 0.88,
    stasisStatus: 'ACTIVE / STABLE',
    logo: '/assets/stocks/logo/nila_systems.png',
    banner: '/assets/stocks/banner/nila_systems.png',
    description: 'High-Latency Space Mesh, Defense Telemetry & Sovereign Cryptographic Cloud computing enterprise software.',
    scope: 'Operates 42 low-earth orbit communication transponders and provides dedicated quantum-resistant communications infrastructure for the Central Bank and SEBI clearing network.',
    sparkline: [136.2, 137.5, 135.8, 139.1, 140.4, 139.8, 142.5],
    fundamentals: {
      revenue: '840.5M ARTH',
      netIncome: '215.2M ARTH',
      operatingMargin: '25.6%',
      totalAssets: '3.42B ARTH',
      totalDebt: '410.0M ARTH',
      freeCashFlow: '184.6M ARTH',
      roe: '18.4%',
      esgScore: 92,
    },
  },
  ARKA: {
    symbol: 'ARKA',
    name: 'Arka Energy Sovereign',
    isin: 'INE122K01024',
    sector: 'Renewable Solar & Hydrogen',
    category: 'Energy',
    price: 164.80,
    change: 9.05,
    changePercent: 5.80,
    isPositive: true,
    marketCap: '3.12B ARTH',
    marketCapNum: 3120000000,
    pe: 21.2,
    eps: 7.78,
    divYield: 2.10,
    volume24h: '980K',
    volume24hNum: 980000,
    turnover: '161.5M ARTH',
    high24h: 166.50,
    low24h: 157.20,
    low52w: 110.00,
    high52w: 172.40,
    beta: 0.92,
    stasisStatus: 'ACTIVE / STABLE',
    logo: '/assets/stocks/logo/arka_energy.png',
    banner: '/assets/stocks/banner/arka_energy.png',
    description: 'National solar grid operator, green hydrogen manufacturing, and sovereign thermal storage infrastructure.',
    scope: 'Monopolistic renewable energy generation utility powering 18 municipal zones and the primary server enclaves of ARTHAX.',
    sparkline: [154.0, 156.2, 155.1, 158.4, 160.0, 162.3, 164.8],
    fundamentals: {
      revenue: '1.18B ARTH',
      netIncome: '286.0M ARTH',
      operatingMargin: '24.2%',
      totalAssets: '4.85B ARTH',
      totalDebt: '890.0M ARTH',
      freeCashFlow: '210.4M ARTH',
      roe: '16.9%',
      esgScore: 96,
    },
  },
  TRNG: {
    symbol: 'TRNG',
    name: 'Tarang Mobility Ltd',
    isin: 'INE84TRNG018',
    sector: 'Electric Rail & Transit',
    category: 'Infra',
    price: 89.20,
    change: 2.47,
    changePercent: 2.85,
    isPositive: true,
    marketCap: '1.94B ARTH',
    marketCapNum: 1940000000,
    pe: 18.6,
    eps: 4.80,
    divYield: 1.80,
    volume24h: '840K',
    volume24hNum: 840000,
    turnover: '74.9M ARTH',
    high24h: 90.40,
    low24h: 86.80,
    low52w: 64.50,
    high52w: 94.00,
    beta: 0.85,
    stasisStatus: 'ACTIVE / STABLE',
    logo: '/assets/stocks/logo/tarang_mobility.png',
    banner: '/assets/stocks/banner/tarang_mobility.png',
    description: 'High-speed electric passenger and industrial freight locomotives, automated metro rails, and smart logistics.',
    scope: 'Sole concessionaire for the Inter-City High Speed Freight Corridor connecting Nava, Setu, and Samaya metropolitan areas.',
    sparkline: [85.0, 86.2, 85.8, 87.1, 88.0, 87.9, 89.2],
    fundamentals: {
      revenue: '920.0M ARTH',
      netIncome: '184.2M ARTH',
      operatingMargin: '20.0%',
      totalAssets: '3.10B ARTH',
      totalDebt: '620.0M ARTH',
      freeCashFlow: '142.8M ARTH',
      roe: '14.2%',
      esgScore: 88,
    },
  },
  VEDA: {
    symbol: 'VEDA',
    name: 'Veda Health Sciences',
    isin: 'INE55VEDA021',
    sector: 'Genomics & Life Sciences',
    category: 'Health',
    price: 215.00,
    change: 2.34,
    changePercent: 1.10,
    isPositive: true,
    marketCap: '2.45B ARTH',
    marketCapNum: 2450000000,
    pe: 28.4,
    eps: 7.57,
    divYield: 1.20,
    volume24h: '410K',
    volume24hNum: 410000,
    turnover: '88.1M ARTH',
    high24h: 218.00,
    low24h: 212.50,
    low52w: 168.00,
    high52w: 226.50,
    beta: 0.65,
    stasisStatus: 'ACTIVE / STABLE',
    logo: '/assets/stocks/logo/veda_health.png',
    banner: '/assets/stocks/banner/veda_health.png',
    description: 'Precision oncology, automated robotic diagnostics, and sovereign national pharmaceutical reserves.',
    scope: 'Holds sovereign patents for critical biological countermeasures and manages the national pharmaceutical repository.',
    sparkline: [210.0, 211.5, 209.8, 213.0, 212.8, 214.2, 215.0],
    fundamentals: {
      revenue: '780.0M ARTH',
      netIncome: '198.4M ARTH',
      operatingMargin: '25.4%',
      totalAssets: '2.95B ARTH',
      totalDebt: '210.0M ARTH',
      freeCashFlow: '165.2M ARTH',
      roe: '21.5%',
      esgScore: 94,
    },
  },
  MERU: {
    symbol: 'MERU',
    name: 'Meru Capital Reserve',
    isin: 'INE338M01019',
    sector: 'Merchant & Reserve Banking',
    category: 'Banking',
    price: 512.00,
    change: 15.85,
    changePercent: 3.20,
    isPositive: true,
    marketCap: '4.20B ARTH',
    marketCapNum: 4200000000,
    pe: 14.5,
    eps: 35.31,
    divYield: 3.40,
    volume24h: '620K',
    volume24hNum: 620000,
    turnover: '317.4M ARTH',
    high24h: 516.80,
    low24h: 498.00,
    low52w: 395.00,
    high52w: 528.00,
    beta: 0.74,
    stasisStatus: 'ACTIVE / STABLE',
    logo: '/assets/stocks/logo/meru_capital.png',
    banner: '/assets/stocks/banner/meru_capital.png',
    description: 'Venture capital consortium, corporate underwriting, liquidity syndication, and private merchant equity.',
    scope: 'Principal market maker on the ARTHAX Stock Exchange, providing liquidity tranches across all 10 listed securities.',
    sparkline: [490.0, 495.2, 498.0, 502.5, 505.0, 508.4, 512.0],
    fundamentals: {
      revenue: '1.45B ARTH',
      netIncome: '480.0M ARTH',
      operatingMargin: '33.1%',
      totalAssets: '9.80B ARTH',
      totalDebt: '1.80B ARTH',
      freeCashFlow: '412.0M ARTH',
      roe: '19.8%',
      esgScore: 90,
    },
  },
  KSHT: {
    symbol: 'KSHT',
    name: 'Kshiti Infra Ports',
    isin: 'INE663K01015',
    sector: 'Deep-Sea Ports & Smart Cities',
    category: 'Infra',
    price: 340.50,
    change: -2.23,
    changePercent: -0.65,
    isPositive: false,
    marketCap: '2.15B ARTH',
    marketCapNum: 2150000000,
    pe: 19.8,
    eps: 17.20,
    divYield: 2.25,
    volume24h: '380K',
    volume24hNum: 380000,
    turnover: '129.4M ARTH',
    high24h: 344.00,
    low24h: 338.50,
    low52w: 280.00,
    high52w: 375.00,
    beta: 0.95,
    stasisStatus: 'ACTIVE / STABLE',
    logo: '/assets/stocks/logo/kshiti_infra.png',
    banner: '/assets/stocks/banner/kshiti_infra.png',
    description: 'Deepwater container terminals, automated maritime logistics, smart industrial corridors, and bridges.',
    scope: 'Concession holder for all 3 maritime international sea gates handling 94% of sovereign international trade.',
    sparkline: [348.0, 345.5, 346.0, 344.2, 342.0, 341.5, 340.5],
    fundamentals: {
      revenue: '860.0M ARTH',
      netIncome: '192.5M ARTH',
      operatingMargin: '22.4%',
      totalAssets: '4.20B ARTH',
      totalDebt: '980.0M ARTH',
      freeCashFlow: '155.0M ARTH',
      roe: '13.5%',
      esgScore: 86,
    },
  },
  AROHA: {
    symbol: 'AROHA',
    name: 'Aroha Foods Sovereign',
    isin: 'INE440F01021',
    sector: 'Agritech & Food Logistics',
    category: 'Equities',
    price: 78.40,
    change: 0.74,
    changePercent: 0.95,
    isPositive: true,
    marketCap: '1.12B ARTH',
    marketCapNum: 1120000000,
    pe: 16.4,
    eps: 4.78,
    divYield: 3.10,
    volume24h: '520K',
    volume24hNum: 520000,
    turnover: '40.8M ARTH',
    high24h: 79.20,
    low24h: 77.50,
    low52w: 56.00,
    high52w: 86.50,
    beta: 0.62,
    stasisStatus: 'ACTIVE / STABLE',
    logo: '/assets/stocks/logo/aroha_foods.png',
    banner: '/assets/stocks/banner/aroha_foods.png',
    description: 'Precision vertical farming, national grain reserves, cold-chain refrigeration networks, and organic staple distribution.',
    scope: 'Maintains the strategic dietary food buffer mandated under Central Bank Sovereign Security Directives.',
    sparkline: [76.5, 77.0, 76.8, 77.4, 78.0, 77.9, 78.4],
    fundamentals: {
      revenue: '640.0M ARTH',
      netIncome: '124.0M ARTH',
      operatingMargin: '19.4%',
      totalAssets: '1.85B ARTH',
      totalDebt: '240.0M ARTH',
      freeCashFlow: '98.5M ARTH',
      roe: '15.8%',
      esgScore: 91,
    },
  },
  ANVIK: {
    symbol: 'ANVIK',
    name: 'Anvik Heavy Industries',
    isin: 'INE771A01033',
    sector: 'Defense & Heavy Alloys',
    category: 'Defense',
    price: 95.30,
    change: 1.36,
    changePercent: 1.45,
    isPositive: true,
    marketCap: '1.68B ARTH',
    marketCapNum: 1680000000,
    pe: 17.8,
    eps: 5.35,
    divYield: 2.05,
    volume24h: '470K',
    volume24hNum: 470000,
    turnover: '44.8M ARTH',
    high24h: 96.40,
    low24h: 93.80,
    low52w: 72.00,
    high52w: 104.00,
    beta: 1.05,
    stasisStatus: 'ACTIVE / STABLE',
    logo: '/assets/stocks/logo/anvik_ind.png',
    banner: '/assets/stocks/banner/anvik_industries.png',
    description: 'Titanium forge manufacturing, heavy hydraulic presses, armored defense alloys, and deep-well drilling rigs.',
    scope: 'Primary defense contractor producing hardened ballistic shelters, deep-earth utility tunnels, and naval hull structures.',
    sparkline: [92.0, 93.4, 93.0, 94.2, 94.8, 94.5, 95.3],
    fundamentals: {
      revenue: '790.0M ARTH',
      netIncome: '158.0M ARTH',
      operatingMargin: '20.0%',
      totalAssets: '2.40B ARTH',
      totalDebt: '390.0M ARTH',
      freeCashFlow: '115.0M ARTH',
      roe: '14.8%',
      esgScore: 84,
    },
  },
  JALA: {
    symbol: 'JALA',
    name: 'Jala Water Utilities',
    isin: 'INE552J01012',
    sector: 'Municipal Filtration & Hydro',
    category: 'Infra',
    price: 64.20,
    change: 0.58,
    changePercent: 0.91,
    isPositive: true,
    marketCap: '940M ARTH',
    marketCapNum: 940000000,
    pe: 15.2,
    eps: 4.22,
    divYield: 3.80,
    volume24h: '310K',
    volume24hNum: 310000,
    turnover: '19.9M ARTH',
    high24h: 65.00,
    low24h: 63.40,
    low52w: 48.00,
    high52w: 69.50,
    beta: 0.55,
    stasisStatus: 'ACTIVE / STABLE',
    logo: '/assets/stocks/logo/jala_water.png',
    banner: '/assets/stocks/banner/manvik_developers.png',
    description: 'Desalination plants, municipal aquifer management, automated membrane filtration, and hydro reservoirs.',
    scope: 'Regulated utility providing purified drinking water to 9 sovereign municipalities and industrial cooling arrays.',
    sparkline: [62.8, 63.2, 63.0, 63.6, 63.9, 64.0, 64.2],
    fundamentals: {
      revenue: '480.0M ARTH',
      netIncome: '96.0M ARTH',
      operatingMargin: '20.0%',
      totalAssets: '1.65B ARTH',
      totalDebt: '290.0M ARTH',
      freeCashFlow: '82.0M ARTH',
      roe: '12.8%',
      esgScore: 95,
    },
  },
  PRAVA: {
    symbol: 'PRAVA',
    name: 'Prava Retail Omnichannel',
    isin: 'INE882P01017',
    sector: 'Nationwide Supermarkets',
    category: 'Equities',
    price: 118.60,
    change: 1.80,
    changePercent: 1.54,
    isPositive: true,
    marketCap: '1.74B ARTH',
    marketCapNum: 1740000000,
    pe: 22.5,
    eps: 5.27,
    divYield: 1.95,
    volume24h: '690K',
    volume24hNum: 690000,
    turnover: '81.8M ARTH',
    high24h: 120.40,
    low24h: 116.50,
    low52w: 84.00,
    high52w: 126.00,
    beta: 0.78,
    stasisStatus: 'ACTIVE / STABLE',
    logo: '/assets/stocks/logo/prava_retail.png',
    banner: '/assets/stocks/banner/prava_reatil.png',
    description: 'Omnichannel department stores, automated grocery fulfillment hubs, and consumer goods distribution.',
    scope: 'Operates 280 hypermarkets and instant fulfillment micro-depots accepting ARTH directly at electronic point of sale.',
    sparkline: [114.0, 115.5, 115.0, 116.8, 117.4, 117.9, 118.6],
    fundamentals: {
      revenue: '1.24B ARTH',
      netIncome: '185.0M ARTH',
      operatingMargin: '14.9%',
      totalAssets: '2.10B ARTH',
      totalDebt: '310.0M ARTH',
      freeCashFlow: '128.0M ARTH',
      roe: '17.2%',
      esgScore: 89,
    },
  },
};

export interface OrderBookEntry {
  price: number;
  qty: number;
  total: number;
  depthPercent: number;
}

export const SAMPLE_ORDER_BOOK: { bids: OrderBookEntry[]; asks: OrderBookEntry[] } = {
  bids: [
    { price: 142.50, qty: 1500, total: 213750, depthPercent: 88 },
    { price: 142.40, qty: 2800, total: 398720, depthPercent: 94 },
    { price: 142.20, qty: 1200, total: 170640, depthPercent: 62 },
    { price: 142.00, qty: 4500, total: 639000, depthPercent: 100 },
    { price: 141.80, qty: 2100, total: 297780, depthPercent: 74 },
    { price: 141.50, qty: 1850, total: 261775, depthPercent: 68 },
  ],
  asks: [
    { price: 142.60, qty: 1100, total: 156860, depthPercent: 58 },
    { price: 142.80, qty: 2400, total: 342720, depthPercent: 82 },
    { price: 143.00, qty: 3800, total: 543400, depthPercent: 96 },
    { price: 143.20, qty: 1900, total: 272080, depthPercent: 70 },
    { price: 143.50, qty: 4200, total: 602700, depthPercent: 100 },
    { price: 143.80, qty: 2600, total: 373880, depthPercent: 78 },
  ],
};

export interface TradeBlotterOrder {
  id: string;
  timestamp: string;
  symbol: string;
  companyName: string;
  isin: string;
  side: 'BUY' | 'SELL';
  orderType: 'Limit' | 'Market' | 'Stop';
  qtyFilled: number;
  qtyTotal: number;
  limitPrice: number;
  executedValue: number;
  status: 'DvP Cleared' | 'Working' | 'Pending CLS' | 'Cancelled';
  settlementRail: string;
  auditHash: string;
}

export const SAMPLE_BLOTTER_ORDERS: TradeBlotterOrder[] = [
  {
    id: '#ORD-89421-DV',
    timestamp: '14:38:12 UTC',
    symbol: 'NILA',
    companyName: 'NILA Systems Ltd',
    isin: 'INE094J01018',
    side: 'BUY',
    orderType: 'Limit',
    qtyFilled: 250,
    qtyTotal: 250,
    limitPrice: 142.50,
    executedValue: 35625.00,
    status: 'DvP Cleared',
    settlementRail: 'SETU Rail #04',
    auditHash: 'SHA256-DVP-98a1-c81f',
  },
  {
    id: '#ORD-89419-DV',
    timestamp: '14:35:01 UTC',
    symbol: 'TRNG',
    companyName: 'Tarang Mobility Ltd',
    isin: 'INE84TRNG018',
    side: 'BUY',
    orderType: 'Limit',
    qtyFilled: 120,
    qtyTotal: 300,
    limitPrice: 48.20,
    executedValue: 14460.00,
    status: 'Working',
    settlementRail: 'Auction Tier-2',
    auditHash: 'SHA256-DVP-77a4-bb20',
  },
  {
    id: '#ORD-89410-DV',
    timestamp: '14:18:44 UTC',
    symbol: 'VEDA',
    companyName: 'Veda Health Sciences',
    isin: 'INE55VEDA021',
    side: 'SELL',
    orderType: 'Market',
    qtyFilled: 100,
    qtyTotal: 100,
    limitPrice: 215.00,
    executedValue: 21500.00,
    status: 'DvP Cleared',
    settlementRail: 'SETU Rail #01',
    auditHash: 'SHA256-DVP-34f1-09de',
  },
  {
    id: '#ORD-89392-DV',
    timestamp: '13:52:10 UTC',
    symbol: 'ARKA',
    companyName: 'Arka Energy Sovereign',
    isin: 'INE122K01024',
    side: 'BUY',
    orderType: 'Limit',
    qtyFilled: 400,
    qtyTotal: 400,
    limitPrice: 164.80,
    executedValue: 65920.00,
    status: 'DvP Cleared',
    settlementRail: 'SETU Rail #03',
    auditHash: 'SHA256-DVP-11e2-ff84',
  },
  {
    id: '#ORD-89380-DV',
    timestamp: '13:40:22 UTC',
    symbol: 'MERU',
    companyName: 'Meru Capital Reserve',
    isin: 'INE338M01019',
    side: 'BUY',
    orderType: 'Limit',
    qtyFilled: 50,
    qtyTotal: 50,
    limitPrice: 512.00,
    executedValue: 25600.00,
    status: 'DvP Cleared',
    settlementRail: 'SETU Rail #02',
    auditHash: 'SHA256-DVP-88b9-4321',
  },
  {
    id: '#ORD-89375-DV',
    timestamp: '13:20:00 UTC',
    symbol: 'KSHT',
    companyName: 'Kshiti Infra Ports',
    isin: 'INE663K01015',
    side: 'SELL',
    orderType: 'Stop',
    qtyFilled: 200,
    qtyTotal: 200,
    limitPrice: 340.50,
    executedValue: 68100.00,
    status: 'Pending CLS',
    settlementRail: 'Enclave Sign #8',
    auditHash: 'SHA256-DVP-66c3-1289',
  },
];

export interface RealizedTaxRecord {
  id: string;
  symbol: string;
  companyName: string;
  holdingPeriod: 'Short-Term (STCG)' | 'Long-Term (LTCG)';
  executionDate: string;
  qty: number;
  costBasis: number;
  salePrice: number;
  realizedProceeds: number;
  netProfit: number;
  taxRate: number; // e.g. 15% or 10%
  taxWithheld: number;
  status: 'Withheld & Remitted' | 'Offset Available' | 'Settling';
}

export const SAMPLE_TAX_RECORDS: RealizedTaxRecord[] = [
  {
    id: '#TAX-2024-9102',
    symbol: 'NILA',
    companyName: 'NILA Systems Ltd',
    holdingPeriod: 'Short-Term (STCG)',
    executionDate: '12 Feb 2025',
    qty: 200,
    costBasis: 110.00,
    salePrice: 142.50,
    realizedProceeds: 28500.00,
    netProfit: 6500.00,
    taxRate: 15,
    taxWithheld: 975.00,
    status: 'Withheld & Remitted',
  },
  {
    id: '#TAX-2024-8841',
    symbol: 'ARKA',
    companyName: 'Arka Energy Sovereign',
    holdingPeriod: 'Long-Term (LTCG)',
    executionDate: '28 Jan 2025',
    qty: 350,
    costBasis: 115.00,
    salePrice: 164.80,
    realizedProceeds: 57680.00,
    netProfit: 17430.00,
    taxRate: 10,
    taxWithheld: 1743.00,
    status: 'Withheld & Remitted',
  },
  {
    id: '#TAX-2024-7740',
    symbol: 'MERU',
    companyName: 'Meru Capital Reserve',
    holdingPeriod: 'Short-Term (STCG)',
    executionDate: '14 Jan 2025',
    qty: 60,
    costBasis: 420.00,
    salePrice: 512.00,
    realizedProceeds: 30720.00,
    netProfit: 5520.00,
    taxRate: 15,
    taxWithheld: 828.00,
    status: 'Withheld & Remitted',
  },
  {
    id: '#TAX-2024-6512',
    symbol: 'KSHT',
    companyName: 'Kshiti Infra Ports',
    holdingPeriod: 'Short-Term (STCG)',
    executionDate: '02 Jan 2025',
    qty: 150,
    costBasis: 360.00,
    salePrice: 340.50,
    realizedProceeds: 51075.00,
    netProfit: -2925.00,
    taxRate: 0,
    taxWithheld: 0.00,
    status: 'Offset Available',
  },
  {
    id: '#TAX-2024-5419',
    symbol: 'ANVIK',
    companyName: 'Anvik Heavy Industries',
    holdingPeriod: 'Long-Term (LTCG)',
    executionDate: '18 Dec 2024',
    qty: 250,
    costBasis: 72.00,
    salePrice: 95.30,
    realizedProceeds: 23825.00,
    netProfit: 5825.00,
    taxRate: 10,
    taxWithheld: 582.50,
    status: 'Withheld & Remitted',
  },
];

export interface ThematicBasket {
  id: string;
  name: string;
  tagline: string;
  cagr3y: string;
  risk: 'Low' | 'Moderate' | 'High';
  minInvestment: number;
  assets: { symbol: string; weight: number }[];
  description: string;
}

export const SAMPLE_BASKETS: ThematicBasket[] = [
  {
    id: 'clean-energy-2030',
    name: 'Clean Energy & Grid 2030',
    tagline: 'Solar, Hydrogen, Water Infrastructure & Thermal Storage',
    cagr3y: '+26.8%',
    risk: 'Moderate',
    minInvestment: 5000,
    assets: [
      { symbol: 'ARKA', weight: 45 },
      { symbol: 'JALA', weight: 30 },
      { symbol: 'TRNG', weight: 25 },
    ],
    description: 'Direct sovereign exposure to green hydrogen generation, solar infrastructure, and high-efficiency hydro grid resilience.',
  },
  {
    id: 'defense-autonomy',
    name: 'Strategic Defense Autonomy',
    tagline: 'High-Latency Space Mesh, Heavy Titanium Alloys & Port Concessions',
    cagr3y: '+21.4%',
    risk: 'Moderate',
    minInvestment: 8000,
    assets: [
      { symbol: 'NILA', weight: 40 },
      { symbol: 'ANVIK', weight: 35 },
      { symbol: 'KSHT', weight: 25 },
    ],
    description: 'Securities basket backing sovereign communications mesh networks, armored metallurgy, and strategic commercial sea gates.',
  },
  {
    id: 'dividend-aristocrats',
    name: 'Sovereign Dividend Aristocrats',
    tagline: 'Cash-flow positive public monopolies with dividend yields > 2.0%',
    cagr3y: '+14.2%',
    risk: 'Low',
    minInvestment: 6000,
    assets: [
      { symbol: 'MERU', weight: 35 },
      { symbol: 'JALA', weight: 30 },
      { symbol: 'AROHA', weight: 20 },
      { symbol: 'PRAVA', weight: 15 },
    ],
    description: 'Prudential defensive allocation focused on regular ARTH cash distributions, zero debt maturities, and stable consumer utility demand.',
  },
  {
    id: 'life-sciences-telemetry',
    name: 'Bio-Genomics & Deep Tech',
    tagline: 'Oncology diagnostics, robotic health hubs, and satellite mesh software',
    cagr3y: '+31.5%',
    risk: 'High',
    minInvestment: 10000,
    assets: [
      { symbol: 'VEDA', weight: 50 },
      { symbol: 'NILA', weight: 35 },
      { symbol: 'ARKA', weight: 15 },
    ],
    description: 'High-alpha sovereign basket investing in next-generation gene therapy patents and quantum encrypted communication networks.',
  },
];
